- name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          proxy_host: ${{ secrets.HOST }}
          proxy_username: ${{ secrets.USERNAME }}
          proxy_password: ${{ secrets.PASSWORD }}
          proxy_command: "cloudflared access ssh-gen --hostname %h"
          script: |
            cd ~/test
            git pull origin main
            make clean
            make
##ad